version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://firstproject.takhleesak.com/api
      - REACT_APP_API_URL_MICROSERVICE2=https://admin.takhleesak.com/api
      - REACT_APP_API_URL_MICROSERVICE3=https://customerservices.takhleesak.com/api
      - REACT_APP_API_URL_MICROSERVICE4=https://user.takhleesak.com/api
      - GENERATE_SOURCEMAP=false 